### ISSUE TITLE
where are they

### ISSUE THREAD

**Issue by beykery** [Consensys/linea-contracts#11]
how can i get the address for 'LineaRollup.sol' contract deployed on ethereum mainnet and goerli testnet ?

**Comment by ddrlunch** [comment]
I have the same Issue, who can help me...

**Comment by 0xfuje** [comment]
> how can i get the address for 'LineaRollup.sol' contract deployed on ethereum mainnet and goerli testnet ?

> I have the same Issue, who can help me

`LineaRollup.sol` inherits `L1MessageService.sol` so it's the L1 Message Service contract displayed in the docs: https://docs.linea.build/use-mainnet/info-contracts

Mainnet addresses:
- Proxy contract: [0xd19d4B5d358258f05D7B411E21A1460D11B0876F](https://etherscan.io/address/0xd19d4b5d358258f05d7b411e21a1460d11b0876f)
- Current implementation contract: [0x934dd4c63e285551cecef8459103554d0096c179](https://etherscan.io/address/0x934dd4c63e285551cecef8459103554d0096c179#code)

**Comment by beykery** [comment]
yes  , but how about goerli testnet ? @0xfuje
